services:
  new_nest_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser123
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"

# sudo docker-compose -f docker-compose.yml up --build -d